#!/bin/bash

tempfiles=( )
function cleanup() {
    $RM -f "${tempfiles[@]}"
}
trap cleanup 0

if ! $DEBUG; then
  # Start log interception
  log=`mktemp`
  tempfiles += ( "$log" )
  exec &> $log
fi

echo "Subject: Update system"
echo " "

echo "*******************************************"
echo "*** emerge --sync"
echo "*******************************************"
echo " "

emerge --sync


echo " "
echo "*******************************************"
echo "*** emerge --oneshot --update portage"
echo "*******************************************"
echo " "

emerge --oneshot --update portage


echo " "
echo "*******************************************"
echo "*** layman -S"
echo "*******************************************"
echo " "

layman -S


echo " "
echo "*******************************************"
echo "*** emerge -uvDN -q world"
echo "*******************************************"
echo " "

emerge -uvDN -q --exclude lrzsz @world


echo " "
echo "*******************************************"
echo "*** emerge @preserved-rebuild"
echo "*******************************************"
echo " "

emerge @preserved-rebuild


echo " "
echo "*******************************************"
echo "*** etc-update"
echo "*******************************************"
echo " "

echo -1 | etc-update


echo " "
echo "*******************************************"
echo "*** revdep-rebuild"
echo "*******************************************"
echo " "

revdep-rebuild


echo " "
echo "*******************************************"
echo "*** perl-cleaner"
echo "*******************************************"
echo " "

perl-cleaner --all
revdep-rebuild

echo " "
echo "*******************************************"
echo "*** emerge -c"
echo "*******************************************"
echo " "

emerge -c

echo " " 
echo " "
echo "***"
echo "*** FINISHED"
echo "***"

if ! $DEBUG; then
  # ferme le fichier de log
  exec &>/dev/null
  SUBJECT="$(hostname): Recap upgrade gentoo"
  MAILTO="To: sebastien@homedruon.com"

  PRECONTENT="From: Automated Gentoo Updated <gentoo-updater>\nSubject: $SUBJECT\n$MAILTO"
  POSTCONTENT="\n\nKindly,\n-- \nThe Gentoo Updater on\n"`hostname -f`"\n."

  mail=`mktemp`
  tempfiles+=( "$mail" )
  echo -e $PRECONTENT > $mail
  /bin/cat $log >> $mail
  echo -e $POSTCONTENT >> $mail

  /bin/cat $mail | /usr/sbin/sendmail -t
fi
